notifications:
  email: false

language: python
python:
    - "2.7"

sudo: false

before_install:
    # Setup anaconda
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda

install:
    - conda env create --file environment.yml
    - source activate py2_parcels
    - pip install -e .

before_script: # configure a headless display to test  plot generation
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

script:
    - flake8 parcels
    - flake8 tests
    - parcels_get_examples examples/
    - py.test -v -s tests/
    - py.test -v -s --nbval-lax examples/
    - make linkcheck -C docs
