environment:

  matrix:

    - PYTHON: "C:\\Python27-miniconda"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
      ENV_NAME: "environment_py2_win.yml"

    - PYTHON: "C:\\Python36-miniconda"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
      ENV_NAME: "environment_py3_win.yml"

install:
  - "powershell ./appveyor/install_miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "conda update --yes conda"
  - "conda env create -f %ENV_NAME% -n parcels"
  - "activate parcels"
  - "python setup.py install"

build: false

test_script:
  - "flake8 parcels"
  - "flake8 tests"
  - "flake8 examples"
  - "parcels_get_examples examples/"
  - "py.test -v -s tests/"
  - "py.test -v -s --nbval-lax examples/"
