name: py2_parcels
channels:
  - conda-forge
dependencies:
  - python=2.7
  - cachetools>=1.0.0
  - cgen
  - enum34
  - ffmpeg
  - flake8>=2.1.0
  - gcc
  - jupyter
  - matplotlib=2.0.2
  - netcdf4>=1.1.9
  - numpy>=1.9.1
  - progressbar2
  - py>=1.4.27
  - pymbolic
  - python-dateutil
  - scipy>=0.16.0
  - six>=1.10.0
  - xarray>=0.5.1
  - pip:
      - pytest>=2.7.0
      - nbval
