name: py3_parcels
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - cgen>=2020.1
  - coverage
  - ffmpeg>=3.2.3
  - flake8>=2.1.0
  - git
  - jupyter
  - m2w64-toolchain
  - matplotlib-base>=2.0.2
  - netcdf4>=1.1.9
  - numpy>=1.9.1
  - psutil
  - py>=1.4.27
  - pymbolic
  - scipy>=0.16.0
  - tqdm
  - xarray>=0.5.1
  - dask<=2022.9.0
  - cftime>=1.3.1
  - ipykernel
  - pytest
  - nbval
  - pykdtree
  - zarr
