name: py3_parcels
channels:
  - conda-forge
dependencies:
  - python>3.4
  - cachetools>=1.0.0
  - cgen>=2020.1
  - coverage
  - ffmpeg>=3.2.3
  - flake8>=2.1.0
  - git
  - jupyter
  - m2w64-toolchain
  - matplotlib>=2.0.2
  - netcdf4>=1.1.9
  - numpy>=1.9.1
  - py>=1.4.27
  - pymbolic
  - python-dateutil
  - scipy>=0.16.0
  - six>=1.10.0
  - tqdm
  - xarray>=0.5.1
  - dask>=2.0
  - cftime>=1.3.1
  - ipykernel<5.0
  - pytest
  - nbval
  - pykdtree
