name: parcels
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - cgen
  - ffmpeg>=3.2.3
  - git
  - jupyter
  - matplotlib-base>=2.0.2
  - netcdf4>=1.1.9
  - numpy>=1.9.1
  - platformdirs
  - psutil
  - py>=1.4.27
  - pymbolic
  - scipy>=0.16.0
  - tqdm
  - trajan
  - xarray>=0.10.8
  - cftime>=1.3.1
  - dask>=2.0
  - nbval
  - scikit-learn
  - pykdtree
  - zarr>=2.11.0

  # Formatting
  - black
  - isort

  # Testing
  - pytest
  - pytest-html
  - coverage

  # Linting
  - flake8>=2.1.0
  - pre_commit
  - pydocstyle

  # Docs
  - ipython
  - numpydoc
  - nbsphinx
  - sphinx<6
  - pandoc>1.12.1,<3
  - pydata-sphinx-theme
  - sphinx-autobuild
  - myst-parser
