name: parcels
channels:
  - conda-forge
dependencies: #! Keep in sync with [tool.pixi.dependencies] in pyproject.toml
  - python>=3.11, <3.13
  - ffmpeg>=3.2.3
  - jupyter
  - matplotlib-base>=2.0.2
  - netcdf4>=1.1.9
  - numpy>=1.9.1
  - psutil
  - pymbolic
  - scipy>=0.16.0
  - tqdm
  - xarray>=0.10.8
  - cftime>=1.3.1
  - dask>=2.0
  - scikit-learn
  - zarr>=2.11.0,!=2.18.0,<3
  - uxarray>=2025.3.0
  - xgcm>=0.9.0
  - pooch
  - cf_xarray

  # Notebooks
  - trajan

  # Testing
  - nbval
  - pytest
  - pytest-html
  - coverage
  - hypothesis

  # Typing
  - mypy
  - lxml # in CI
  - types-tqdm
  - types-psutil

  # Linting
  - pre_commit

  # Docs
  - ipython
  - numpydoc!=1.9.0
  - nbsphinx
  - sphinx
  - pandoc
  - pydata-sphinx-theme
  - sphinx-autobuild
  - myst-parser
  - sphinxcontrib-mermaid
