name: py3_parcels
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - cgen>=2020.1
  - ffmpeg>=3.2.3
  - git
  - jupyter
  - m2w64-toolchain
  - matplotlib-base>=2.0.2
  - netcdf4>=1.1.9
  - numpy>=1.9.1
  - pandas
  - platformdirs
  - psutil
  - py>=1.4.27
  - pymbolic
  - scipy>=0.16.0
  - tqdm
  - trajan
  - xarray>=0.5.1
  - dask<=2022.9.0
  - cftime>=1.3.1
  - ipykernel
  - nbval
  - pykdtree

  # Formatting
  - black
  - isort

  # Testing
  - pytest
  - pytest-html
  - coverage

  # Linting
  - flake8>=2.1.0
  - pre_commit
  - pydocstyle

  # Docs
  - ipython
  - numpydoc
  - nbsphinx
  - sphinx<6
  - pandoc>1.12.1,<3
  - pydata-sphinx-theme
  - sphinx-autobuild
  - myst-parser
