contact_links:
  - name: ğŸ™ Parcels use question, help, or support
    url: https://github.com/OceanParcels/parcels/discussions/new?category=q-a
    about: Have a question about Parcels? Or do you need troubleshooting for a specific usecase? Then start a Q&A Discussion thread instead, and we'll be happy to help.
  - name: ğŸ’¬ Other Parcels discussion
    url: https://github.com/OceanParcels/parcels/discussions
    about: For general discussion about Parcels, or to share your work with the community, please use the Discussions tab.
